<?php 
include ("header.php");
?>
          <!-- Page titlebar start -->
          <div class="content-section decorated-bg page-titlebar">
            <div class="container">
              <div class="row">
                <div class="col-lg-12">
                  <h1 class="title">Free Estimate</h1>
                  <ol class="breadcrumb">
                    <li>
                      <a href="#">Home</a>
                    </li>
                    <li>
                      <a href="#">Free Estimate</a>
                    </li>
                  </ol>
                </div>
              </div>
            </div>
          </div>
          <!-- Page titlebar end -->
                   <!-- intro and benifits start -->
          <div class="content-section">
            <div class="container">
              <div class="row">
                <div class="col-xs-12">
                  <div class="content-section-header center">
                    <h2 class="title">Request Your Free Estimate</h2>
                    <p class="description">If you’re unsure about which Creative Enterprises will fit your needs, contact the experts at Window Film Depot. We can help you select just the right films for your project, with on-time delivery, and the industry’s highest rated installation services.<br>

                    Once filling out the form below and submitting to Window Film Depot, the process to quantify the energy savings begins. An energy analysis and payback report can be generated by Window Film Depot in as little as 24 hours and ready for review by your energy management team.</p>
                  </div>
                  <!-- <div id="button"><h5>+ Read More</h5></div> -->
                  <style type="text/css">
                  hr {
                  width: 100%;
                  height: 3px;
                  background-color:#02124d;
                  margin-right: auto;
                  margin-left: auto;
                  margin-top: 5px;
                  margin-bottom: 5px;
                  /*border-width: 2px;*/
                  /*border-color: green;*/
                  }
                </style>
                <hr>
                <br>
                  <div class="content-section-header center" id="hide">
                      <div class="container" style="margin-left: 100px;">
                          <div class="row">
                              <div class="col-md-5">
                                <input type="text" name="name" class="form-control" placeholder="First Name">
                              </div>
                              <div class="col-md-5">
                                <input type="text" name="name" class="form-control" placeholder="Last Name">
                              </div>
                          </div>
                          <br>
                          <div class="row">
                              <div class="col-md-5">
                                <input type="text" name="name" class="form-control" placeholder="Company">
                              </div>
                              <div class="col-md-5">
                                <input type="text" name="name" class="form-control" placeholder="State">
                              </div>
                          </div>
                          <br>
                          <div class="row">
                              <div class="col-md-5">
                                <input type="text" name="name" class="form-control" placeholder="City">
                              </div>
                              <div class="col-md-5">
                                <input type="text" name="name" class="form-control" placeholder="Zip Code">
                              </div>
                          </div>
                          <br>
                          <div class="row">
                              <div class="col-md-5">
                                <input type="text" name="name" class="form-control" placeholder="Email ">
                              </div>
                              <div class="col-md-5">
                                <input type="text" name="name" class="form-control" placeholder="Phone">
                              </div>
                          </div>
                          <br>
                          <div class="row">
                              <div class="col-md-5">
                                <select class="form-control">
                                    <option>How Many Window Need Treatment</option>
                                    <option>0-25</option>
                                    <option>26-50</option>
                                    <option>Over 50</option>
                                    <option>Multiple Locations</option>
                                </select>
                              </div>
                              <div class="col-md-5">
                                <select class="form-control"> 
                                    <option>What Type Of products are you intrested in?</option>
                                    <option>I'm not sure</option>
                                    <option>Sun Control</option>
                                    <option>Security</option>
                                    <option>Decorative</option>
                                </select>
                              </div>
                          </div>
                          <br>
                          <div class="row">
                              <div class="col-md-5">
                                <select class="form-control">
                                    <option>Do You Need Installation?</option>
                                    <option>Yes</option>
                                    <option>No</option>
                                </select>
                              </div>
                              <div class="col-md-5">
                                <select class="form-control">
                                    <option>Property Type</option>
                                    <option>Commercial</option>
                                    <option>Residential</option>
                                    <option>Retail Property</option>
                                    <option>School</option>
                                    <option>Others</option>
                                </select>
                              </div>
                          </div>
                          <br>
                          <div class="row row-justify-center">
                            <div class="col-md-5" style="margin-left: 500px;">
                              <button class="btn btn-1">Submit</button>
                            </div>
                          </div>
                      </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- intro and benifits end -->
          <!-- Partners start -->
         <!--  <div class="content-section">
            <div class="container">
              <div class="row">
                <div class="col-lg-12">
                  <div class="partners-wrapper">
                    <div class="partners-nav left owl-nav">
                      <button id="partners-prev" type="button" role="presentation" class="owl-prev">
                        <span class="wicon-iconmonstr-angel-left-circle-thin"></span>
                      </button>
                    </div>
                    <div id="partners" class="partners-content owl-carousel owl-theme">
                      <img src="../../images/partners/1.png" alt="">
                      <img src="../../images/partners/2.png" alt="">
                      <img src="../../images/partners/3.png" alt="">
                      <img src="../../images/partners/4.png" alt="">
                      <img src="../../images/partners/5.png" alt="">
                      <img src="../../images/partners/6.png" alt="">
                      <img src="../../images/partners/7.png" alt="">
                      <img src="../../images/partners/8.png" alt="">
                      <img src="../../images/partners/9.png" alt="">
                    </div>
                    <div class="partners-nav right owl-nav">
                      <button id="partners-next" type="button" role="presentation" class="owl-next">
                        <span class="wicon-iconmonstr-angel-right-circle-thin"></span>
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div> -->
          <!-- Partners end -->
        </div>
   <?php include("footer.php");?>